version: '3'
services:
  server:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./.docker/server/Dockerfile
    container_name: server
    env_file:
      - server/.env
    ports:
      - 5000:5000
    volumes:
      - ./server/:/app
      - ./server/lib/:/app/lib
  client:
    build:
      context: ./
      dockerfile: ./.docker/client/Dockerfile
    ports:
      - "3000:3000"
    container_name: client
    volumes:
       - ./client/:/app
       - ./client/node_modules/:/app/node_modules/

